services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bitespeed_db
      POSTGRES_USER: bitespeed_user
      POSTGRES_PASSWORD: bitespeed_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://bitespeed_user:bitespeed_password@postgres:5432/bitespeed_db"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "sleep 10 && npx prisma db push && npm start"

volumes:
  postgres_data:
