services:
  - type: web
    name: bitespeed-identity-service
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-postgres
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: bitespeed-postgres
    plan: free
    databaseName: bitespeed_identity
    user: bitespeed_user
